"""Machine state as non-overlapping intervals, enforced by the database.

The natural shape for "what was this machine doing" is a sample every minute,
and it is the wrong one. Samples cannot answer "how long was it working"
without assuming the gap between them, they cannot represent a state that
started between two samples, and two processes writing the same minute produce
two rows that quietly disagree rather than a conflict.

Intervals answer utilisation by range arithmetic instead, and the exclusion
constraint makes "a machine is in exactly one state at a time" a property of the
schema rather than a property of whichever code last wrote to it.

Revision ID: 0002_state_intervals
Revises: 0001_registry
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0002_state_intervals"
down_revision: str | None = "0001_registry"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE fleet.machine_state_interval (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            serial text NOT NULL REFERENCES fleet.machine(serial),
            state text NOT NULL,
            period tstzrange NOT NULL,
            -- The range is authoritative; these two are conveniences for
            -- queries and for anyone reading the table by eye. Generated rather
            -- than written, so they cannot drift from the range they describe.
            started_at timestamptz GENERATED ALWAYS AS (lower(period)) STORED,
            ended_at timestamptz GENERATED ALWAYS AS (upper(period)) STORED,

            CONSTRAINT machine_state_known
                CHECK (state IN ('working', 'transit', 'idle_on', 'off')),

            -- An unbounded or empty interval breaks every duration sum built on
            -- this table, and does so silently: sum(upper - lower) over an
            -- infinite range is infinity, and over an empty one is zero.
            CONSTRAINT machine_state_bounded CHECK (
                NOT lower_inf(period) AND NOT upper_inf(period) AND NOT isempty(period)
            ),

            -- Half-open, always. With inclusive upper bounds two adjacent
            -- intervals share their boundary instant, the exclusion constraint
            -- rejects the pair, and the machine can never change state.
            CONSTRAINT machine_state_half_open CHECK (
                lower_inc(period) AND NOT upper_inc(period)
            ),

            CONSTRAINT machine_state_no_overlap
                EXCLUDE USING gist (serial WITH =, period WITH &&)
        )
    """)

    op.execute(
        "COMMENT ON TABLE fleet.machine_state_interval IS "
        "'What each machine was doing, as intervals rather than samples. "
        "Utilisation is range arithmetic over this table. A machine is in exactly "
        "one state at any instant, enforced by machine_state_no_overlap.'"
    )
    op.execute(
        "COMMENT ON CONSTRAINT machine_state_no_overlap ON fleet.machine_state_interval IS "
        "'Two intervals for one serial may not overlap. Needs btree_gist: the "
        "constraint mixes plain equality on serial with range overlap on period.'"
    )

    # The exclusion constraint's GiST index answers "which interval covers this
    # instant" but is poor at "this machine, ordered by time", which is what
    # every rollup does.
    op.execute("""
        CREATE INDEX machine_state_serial_time_idx
        ON fleet.machine_state_interval (serial, started_at)
    """)
    op.execute("""
        CREATE INDEX machine_state_state_idx
        ON fleet.machine_state_interval (state, started_at)
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fleet.machine_state_interval")
